# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-06 19:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('total_contributed', models.FloatField()),
                ('pac_contributions', models.FloatField()),
                ('individual_contributions', models.FloatField()),
            ],
        ),
    ]
