# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-13 21:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='NPRStory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=250)),
                ('title', models.CharField(max_length=250)),
            ],
        ),
    ]
