# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-19 21:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('members', '0006_auto_20160319_1227'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savedmemberdetail',
            name='user',
        ),
        migrations.AddField(
            model_name='legislator',
            name='saved_by',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='SavedMemberDetail',
        ),
    ]
